### ISSUE TITLE
Could not find a version that satisfies the requirement body-visualizer

### ISSUE THREAD

**Issue by AbdullahJames** [EricGuo5513/HumanML3D#10]
I'm getting this error:

```
E:\AI\HumanML3D>conda env create -f environment.yaml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 22.9.0

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['C:\\Users\\Abdullah\\miniconda3\\envs\\torch_render\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'E:\\AI\\HumanML3D\\condaenv.842xv54t.requirements.txt']
Pip subprocess output:
Collecting absl-py==1.0.0
  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement body-visualizer
ERROR: No matching distribution found for body-visualizer

failed

CondaEnvException: Pip failed


E:\AI\HumanML3D>
```

**Comment by Dene33** [comment]
I'm having the same problem.

**Comment by Dene33** [comment]
Actually, the better way is to change the environment.yaml. 

Change `body-visualizer==1.1.0` to `git+https://github.com/nghorbani/body_visualizer.git`
and
`psbody-mesh==0.4` to `git+https://github.com/MPI-IS/mesh.git`

**Comment by katsully** [comment]
I'm stilling have issues installing psbody-mesh
 `ERROR: Failed building wheel for psbody-mesh`
Anyone else?

**Comment by Kadah** [comment]
Also `configer==1.4.1`, seems the newest on pypi is 1.3.1.

So the following need to be installed manually, or updated to point to git instead in envro yml:
```
body-visualizer==1.1.0
configer==1.4.1
psbody-mesh==0.4
```
```
pip install git+https://github.com/nghorbani/body_visualizer.git
pip install git+https://github.com/MPI-IS/configer
pip install git+https://github.com/MPI-IS/mesh.git
```

**Comment by EricGuo5513** [comment]
Hi, for anyone who is still struggling with the envionment installation, please send an email to cguo2@ualberta.ca.

**Comment by mmdrahmani** [comment]
Hi 
I am still struggling with psbody mesh installation. None of these worked for me.
pip install git+https://github.com/MPI-IS/mesh.git
pip install psbody-mesh==0.4

I am on Ubuntu 18.04.6 LTS.
Thanks
Mohammad

**Comment by XingliangJin** [comment]
I successfully installed psbody-mesh. Hope these can help you. 
First, run
`sudo apt-get install libboost-dev`
Then
`pip install git+https://github.com/MPI-IS/mesh.git`

**Comment by katsully** [comment]
what helped with psbody-mesh installation issues for me was 
`sudo apt-get install libboost-dev
sudo apt install gcc g++`

**Comment by liujf69** [comment]
In centos8, it work for me.

Remove the following from yaml:
``body-visualizer==1.1.0``
``configer==1.4.1``
``psbody-mesh==0.4``

Replace by:
``pip install git+https://github.com/nghorbani/body_visualizer.git``
``pip install git+https://github.com/MPI-IS/configer``
``sudo yum -y install boost-devel``
``pip install git+https://github.com/MPI-IS/mesh.git``

**Comment by yassineAlouini** [comment]
> I successfully installed psbody-mesh. Hope these can help you. First, run `sudo apt-get install libboost-dev` Then `pip install git+https://github.com/MPI-IS/mesh.git`

This works, thanks!

**Comment by euminds** [comment]
> Hi, for anyone who is still struggling with the envionment installation, please send an email to [cguo2@ualberta.ca](mailto:cguo2@ualberta.ca).

When attempting to run the raw_pose_processing.py script in the torch_render conda environment, I encountered a compatibility issue between PyTorch and the NVIDIA GeForce RTX 3090 GPU related to CUDA capability mismatch. I think it should be updated to a new torch setting. Could you give me some advice?

(torch_render) jintao@dg04:~/rjtproject/HumanML3D$ python raw_pose_processing.py 
/home/jintao/miniconda3/envs/torch_render/lib/python3.7/site-packages/torch/cuda/__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "raw_pose_processing.py", line 91, in <module>
    male_bm = BodyModel(bm_fname=male_bm_path, num_betas=num_betas, num_dmpls=num_dmpls, dmpl_fname=male_dmpl_path).to(comp_device)
  File "/home/jintao/miniconda3/envs/torch_render/lib/python3.7/site-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/home/jintao/miniconda3/envs/torch_render/lib/python3.7/site-packages/torch/nn/modules/module.py", line 402, in _apply
    self._buffers[key] = fn(buf)
  File "/home/jintao/miniconda3/envs/torch_render/lib/python3.7/site-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal

**Comment by Hzh873851987** [comment]
@euminds The cause of the problem is using the wrong device ID
If you only have one graphics card, modify cuda:2 -> cuda:1 in ipynb, which successfully solved the problem for me.
![图片](https://github.com/user-attachments/assets/227bdc98-d3be-4258-8eb5-9c6e88787b0f)

**Comment by kangshwan** [comment]
In my case, install==1.3.5 also caused issues. 
Changing to pip-install==1.3.5 resolved the problem.

**Comment by kangshwan** [comment]
For me, while using Windows 11, `install==1.3.5` also caused issues. 
Changing to `pip-install==1.3.5` resolved the problem.

**Comment by Pokerman8** [comment]
> I'm stilling have issues installing psbody-mesh `ERROR: Failed building wheel for psbody-mesh` Anyone else?

That worked！！Thanks so much.

**Comment by FlyRaytheon** [comment]
I had some issues installing "psbody-mesh", but I solved it with the following:
sudo apt-get install libboost-dev
sudo apt install gcc g++
conda install -c conda-forge gxx_linux-64
sudo apt-get update && sudo apt-get install build-essential
conda install -c conda-forge boost
(Ubuntu 24.04.1 LTS)
