### ISSUE TITLE
FileNotFoundError in raw_pose_processing

### ISSUE THREAD

**Issue by FrankLiu1118** [EricGuo5513/HumanML3D#103]
This is the output:Processed / All (fps 100): 8433/14055
Processing: KIT: 100%|██████████| 4232/4232 [2:26:16<00:00,  2.07s/it]   
Processed / All (fps 100): 12665/14055
Processing: SSM_synced: 100%|██████████| 30/30 [00:19<00:00,  1.53it/s]
Processed / All (fps 120): 12695/14055
Processing: DFaust_67: 100%|██████████| 139/139 [01:27<00:00,  1.60it/s]
Processed / All (fps 60): 12834/14055
Processing: TotalCapture: 100%|██████████| 37/37 [09:36<00:00, 15.59s/it]
Processed / All (fps 60): 12871/14055
Processing: SFU: 100%|██████████| 44/44 [04:13<00:00,  5.76s/it]
Processed / All (fps 120): 12915/14055
Processing: Transitions_mocap: 100%|██████████| 110/110 [02:13<00:00,  1.21s/it]
Processed / All (fps 120): 13025/14055
Processing: Eyes_Japan_Dataset: 100%|██████████| 750/750 [1:25:46<00:00,  6.86s/it]
Processed / All (fps 120): 13775/14055
Processing: HumanEva: 100%|██████████| 28/28 [01:41<00:00,  3.62s/it]
Processed / All (fps 120): 13803/14055
Processing: ACCAD: 100%|██████████| 252/252 [04:35<00:00,  1.09s/it]
Processed / All (fps 120): 14055/14055
  0%|          | 4/14616 [00:00<00:14, 990.62it/s]
Traceback (most recent call last):
  File "/mnt/ssd_1/hongyi/HumanML3D/HumanML3D/raw_pose_processing.py", line 154, in <module>
    data = np.load(source_path)
  File "/home/hyliu/anaconda3/lib/python3.9/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './pose_data/CMU/80/80_63_poses.npy'

**Comment by CMY-CTO** [comment]
![image](https://github.com/EricGuo5513/HumanML3D/assets/58409065/712cfcdb-8560-45c9-b25b-d61d01849b23)
Hi! I also met this problem. How did you solve it? By modifying `index.csv` or modifying the directory level of `./pose/` or others? 
Thank you!

**Comment by biscuit1103** [comment]
> ![图像](https://private-user-images.githubusercontent.com/58409065/299880481-712cfcdb-8560-45c9-b25b-d61d01849b23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzExNjgsIm5iZiI6MTcxMzkzMDg2OCwicGF0aCI6Ii81ODQwOTA2NS8yOTk4ODA0ODEtNzEyY2ZjZGItODU2MC00NWM5LWIyNWItZDYxZDAxODQ5YjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAzNTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNTk0NDZhYmM3NzVmYTZlNzc3OGUyMTMxYzk4N2UyYThlZmRiY2I5MTkzMmEyOTE2NzFmYmJmODA0ZDMxMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BRa6DmsgqAnnk0uv3v36Og_M1l3o0n3dCGA1uq4J6Sg) 你好！我也遇到了这个问题。你是怎么解决的？通过修改`index.csv`或者修改目录级别`./pose/`或者其他？ 谢谢你！

Excuse me, have you solved this problem?

**Comment by HelloWorld416** [comment]
> ![image](https://private-user-images.githubusercontent.com/58409065/299880481-712cfcdb-8560-45c9-b25b-d61d01849b23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDE5OTcsIm5iZiI6MTcyOTI0MTY5NywicGF0aCI6Ii81ODQwOTA2NS8yOTk4ODA0ODEtNzEyY2ZjZGItODU2MC00NWM5LWIyNWItZDYxZDAxODQ5YjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA4NTQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMmNhZGJjYzNlZmI2MjhlYzI1NzcwY2JhMjZhOWQwOGMyNWM5OWY1MThhZWIyNThjYzU5Y2JhMWI1YjNjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j9tqIoyYqobUz806e1SPxP0m9jl_XDaENSGLDRzQU90) Hi! I also met this problem. How did you solve it? By modifying `index.csv` or modifying the directory level of `./pose/` or others? Thank you!

I meet the same problem with you. Have you solved this issue? Could you please help me?

**Comment by Jianrong-Lu** [comment]
I meet the same question, could you tell me the solution？

**Comment by OrangeJuFan** [comment]
> ![image](https://github.com/EricGuo5513/HumanML3D/assets/58409065/712cfcdb-8560-45c9-b25b-d61d01849b23) Hi! I also met this problem. How did you solve it? By modifying `index.csv` or modifying the directory level of `./pose/` or others? Thank you!

你是不是下载的.npz格式的数据集
