### ISSUE TITLE
error in raw_pose_processing

### ISSUE THREAD

**Issue by Suzixin7894946** [EricGuo5513/HumanML3D#105]
Traceback (most recent call last):
  File "raw_pose_processing.py", line 116, in <module>
    fps = amass_to_pose(path, save_path)
  File "raw_pose_processing.py", line 66, in amass_to_pose
    bdata = np.load(src_path, allow_pickle=True)
  File "/public/home/jd_szx/.conda/envs/sssu/lib/python3.7/site-packages/numpy/lib/npyio.py", line 433, in load
    pickle_kwargs=pickle_kwargs)
  File "/public/home/jd_szx/.conda/envs/sssu/lib/python3.7/site-packages/numpy/lib/npyio.py", line 189, in __init__
    _zip = zipfile_factory(fid)
  File "/public/home/jd_szx/.conda/envs/sssu/lib/python3.7/site-packages/numpy/lib/npyio.py", line 112, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/public/home/jd_szx/.conda/envs/sssu/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/public/home/jd_szx/.conda/envs/sssu/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
how to solove??

**Comment by CMY-CTO** [comment]
Hello, I also met this error.
Have you solved this problem? 
Thank you!!!

**Comment by haytham918** [comment]
Encountering the same issue
