### ISSUE TITLE
CUDA Error when running  raw_pose_processing

### ISSUE THREAD

**Issue by euminds** [EricGuo5513/HumanML3D#154]
When attempting to run the raw_pose_processing.py script in the torch_render conda environment, I encountered a compatibility issue between PyTorch and the NVIDIA GeForce RTX 3090 GPU related to CUDA capability mismatch. I think it should be updated to a new torch setting. Could you give me some advice?

(torch_render) jintao@dg04:~/rjtproject/HumanML3D$ python raw_pose_processing.py
/home/jintao/miniconda3/envs/torch_render/lib/python3.7/site-packages/torch/cuda/init.py:104: UserWarning:
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
File "raw_pose_processing.py", line 91, in
male_bm = BodyModel(bm_fname=male_bm_path, num_betas=num_betas, num_dmpls=num_dmpls, dmpl_fname=male_dmpl_path).to(comp_device)
File "/home/jintao/miniconda3/envs/torch_render/lib/python3.7/site-packages/torch/nn/modules/module.py", line 612, in to
return self._apply(convert)
File "/home/jintao/miniconda3/envs/torch_render/lib/python3.7/site-packages/torch/nn/modules/module.py", line 402, in _apply
self._buffers[key] = fn(buf)
File "/home/jintao/miniconda3/envs/torch_render/lib/python3.7/site-packages/torch/nn/modules/module.py", line 610, in convert
return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal

**Comment by Hzh873851987** [comment]
https://github.com/EricGuo5513/HumanML3D/issues/10#issuecomment-2428523001
